name = "sethjenks-wall"
main = "src/index.ts"
compatibility_date = "2026-10-01"
compatibility_flags = ["nodejs_compat"]

[durable_objects]
bindings = [
  { name = "TLDRAW_DURABLE_OBJECT", class_name = "TldrawDurableObject" }
]

[[migrations]]
tag = "v1"
new_sqlite_classes = ["TldrawDurableObject"]

[observability]
enabled = true

[observability.logs]
enabled = true
head_sampling_rate = 1

[observability.traces]
enabled = true
